markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Keep Calm and Carry On"
#markdown: rdiscount

author: "zhang"
atom-baseurl: "http://branchang.github.io"
#disqus: "gopherwood"

remote_theme: pages-themes/hacker
#theme: jekyll-theme-hacker
###
